### ISSUE TITLE
Malformed JSX

### ISSUE THREAD

**Issue by jfurrow** [mapbox/svg-react-transformer#12]
When transforming [this SVG](https://github.com/mapbox/svg-react-transformer/files/1573079/bad-svg.zip), the resulting JSX contains style attributes that have not been transformed (`style="isolation: isolate"` should be `style={{isolation: 'isolate'}}`).

**Comment by jseppi** [comment]
Pretty sure this is because [this call to `.replace`](https://github.com/mapbox/svg-react-transformer/blob/master/packages/svg-react-transformer/lib/to-jsx.js#L45) does not specify the global (`/g`) modifier to the regex.

PR incoming shortly.
